CommandsFileExtension.RegisterCommandGlobal("File", "Open file", ["File to open"])
CommandsFileExtension.RegisterCommandGlobal("Folder", "Open folder", ["Folder to open"])
CommandsFileExtension.RegisterCommandGlobal("Open", "Open website, file etc.", ["What to open (e.g. path)"])
CommandsFileExtension.RegisterCommandGlobal("Search", "Search web", ["URL template. Use REPLACEME for search string"])
CommandsFileExtension.RegisterCommandGlobal("Web", "Open website", ["Website to open"])
CommandsFileExtension.RegisterCommandGlobal("ShowInWindow", "Show text in window", ["Text to show in window"])
CommandsFileExtension.RegisterCommandGlobal("ShowMessage", "Show message", ["Message to show"])
CommandsFileExtension.RegisterCommandGlobal("TypeText", "Type text", ["Text to type"])
