CommandsFileExtension.GetInstance().RegisterCommand("File", "Open file", ["File to open"])
CommandsFileExtension.GetInstance().RegisterCommand("Folder", "Open folder", ["Folder to open"])
CommandsFileExtension.GetInstance().RegisterCommand("Open", "Open website, file etc.", ["What to open (e.g. path)"])
CommandsFileExtension.GetInstance().RegisterCommand("Search", "Search web", ["URL template. Use REPLACEME for search string"])
CommandsFileExtension.GetInstance().RegisterCommand("Web", "Open website", ["Website to open"])
CommandsFileExtension.GetInstance().RegisterCommand("ShowInWindow", "Show text in window", ["Text to show in window"])
CommandsFileExtension.GetInstance().RegisterCommand("ShowMessage", "Show message", ["Message to show"])
CommandsFileExtension.GetInstance().RegisterCommand("TypeText", "Type text", ["Text to type"])
